name: Generate Documentation

on:
  push:
    branches:
      - training_lanes

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: |
            python3 ./scripts/copy_readme.py
            cd doxyfiles
            doxygen Doxyfile

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: doxyfiles/docs
          publish_branch: gh-pages
          force_orphan: true

# name: Generate Documentation

# on:
#   push:
#     branches:
#       - training_lanes

# jobs:
#   generate-docs:
#     name: Generate Documentation
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0  # Full history for accurate commits

#       - name: Install Doxygen
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y doxygen graphviz python3

#       - name: Create Directories
#         run: |
#           mkdir -p doxyfiles/docs
#           mkdir -p docs

#       - name: Run copy_readme.py
#         run: |
#           python3 scripts/copy_readme.py || echo "copy_readme.py failed, continuing..."
#           ls -l doxyfiles/docs

#       - name: Generate Doxygen Documentation
#         run: |
#           cd doxyfiles
#           doxygen Doxyfile
#           ls -l docs

#       - name: Copy Doxygen Output to Root Docs
#         run: |
#           cp -r doxyfiles/docs/* docs/ || echo "No files to copy from doxyfiles/docs"
#           ls -l docs

#       - name: Create .nojekyll and Minimal Files
#         run: |
#           touch docs/.nojekyll
#           mkdir -p docs/assets/css
#           echo "/* Minimal style.scss for Jekyll */" > docs/assets/css/style.scss
#           ls -l docs
#           ls -l docs/assets/css

#       - name: Commit Changes to training_lanes
#         run: |
#           git config user.name "GitHub Actions"
#           git config user.email "actions@github.com"
#           git add docs
#           git commit -m "Update docs folder with Doxygen output" || echo "No changes to commit"
#           git push origin training_lanes

#       - name: Deploy Documentation to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.PAT_TOKEN }}
#           publish_dir: docs
#           publish_branch: training_lanes
#           force_orphan: false