# name: Generate Documentation

# on:
#   push:
#     branches:
#       - training_lanes

# jobs:
#   generate-docs:
#     name: Generate Documentation
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Install Doxygen
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y doxygen graphviz
          
#       - name: Create docs directory if it does not exist
#         run: |
#           mkdir -p docs

#       - name: Generate Documentation
#         run: |
#             python3 ./scripts/copy_readme.py
#             cd doxyfiles
#             doxygen Doxyfile

#       - name: Deploy Documentation to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.PAT_TOKEN }}
#           publish_dir: .
#           force_orphan: true
name: Generate Documentation

on:
  push:
    branches:
      - training_lanes

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz python3

      - name: Create docs directory if it does not exist
        run: |
          mkdir -p doxyfiles/docs

      - name: Generate Documentation
        run: |
          python3 scripts/copy_readme.py
          cd doxyfiles
          doxygen Doxyfile

      - name: Move Doxygen Output to Root Docs
        run: |
          mkdir -p docs
          cp -r doxyfiles/docs/* docs/

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: docs
          publish_branch: training_lanes
          force_orphan: false