var searchData=
[
  ['target_5ffile_0',['target_file',['../namespacecopy__readme.html#a87b872358a9b0db7fcd2d03930abbee3',1,'copy_readme']]],
  ['tensorrt_1',['tensorrt',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2README.html#autotoc_md83',1,'2. Converting YOLO to TensorRT'],['../index.html#autotoc_md11',1,'2. Converting YOLO to TensorRT']]],
  ['test_20coverage_20report_2',['test coverage report',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2README.html#autotoc_md91',1,'Test Coverage Report'],['../index.html#autotoc_md19',1,'Test Coverage Report']]],
  ['test_5fbbox_5fseg_3',['test_bbox_seg',['../namespacetest__bbox__seg.html',1,'']]],
  ['test_5fbbox_5fseg_2epy_4',['test_bbox_seg.py',['../test__bbox__seg_8py.html',1,'']]],
  ['test_5fchange_5fannotation_5flabels_5',['test_change_annotation_labels',['../namespacetest__remap__classid.html#a1d6d883ed708845d02d873dcc6bb221f',1,'test_remap_classid']]],
  ['test_5fcoco_5fto_5ftxt_5fbasic_6',['test_coco_to_txt_basic',['../namespacetest__coco__txt.html#a3543b1fd5a14b73917ced62d918e0a91',1,'test_coco_txt']]],
  ['test_5fcoco_5fto_5ftxt_5fno_5fannotations_7',['test_coco_to_txt_no_annotations',['../namespacetest__coco__txt.html#a86e8cd27f73590000a465f2d6214519f',1,'test_coco_txt']]],
  ['test_5fcoco_5ftxt_8',['test_coco_txt',['../namespacetest__coco__txt.html',1,'']]],
  ['test_5fcoco_5ftxt_2epy_9',['test_coco_txt.py',['../test__coco__txt_8py.html',1,'']]],
  ['test_5fconvert_5fbbox_5fto_5fsegmentation_10',['test_convert_bbox_to_segmentation',['../namespacetest__bbox__seg.html#a9fde245ae104106bf412a8beacbb5d66',1,'test_bbox_seg']]],
  ['test_5fcount_5fclass_5fids_5fbasic_11',['test_count_class_ids_basic',['../namespacetest__count__labels.html#a604777741d765d6dbe06589cba713701',1,'test_count_labels']]],
  ['test_5fcount_5fclass_5fids_5fempty_5ffile_12',['test_count_class_ids_empty_file',['../namespacetest__count__labels.html#a36f6ea761ec01549bdb3ad2dd8916768',1,'test_count_labels']]],
  ['test_5fcount_5flabels_13',['test_count_labels',['../namespacetest__count__labels.html',1,'']]],
  ['test_5fcount_5flabels_2epy_14',['test_count_labels.py',['../test__count__labels_8py.html',1,'']]],
  ['test_5fremap_5fclassid_15',['test_remap_classid',['../namespacetest__remap__classid.html',1,'']]],
  ['test_5fremap_5fclassid_2epy_16',['test_remap_classid.py',['../test__remap__classid_8py.html',1,'']]],
  ['test_5frename_5ffiles_17',['test_rename_files',['../namespacetest__rename__files.html',1,'']]],
  ['test_5frename_5ffiles_2epy_18',['test_rename_files.py',['../test__rename__files_8py.html',1,'']]],
  ['test_5frename_5fimages_5flabels_19',['test_rename_images_labels',['../namespacetest__rename__files.html#a903e1d3a55d2ff163f2aa8e15cd2b339',1,'test_rename_files']]],
  ['test_5ftrain_5fobjects_5fmodel_20',['test_train_objects_model',['../namespacetest__training.html#aa430b1755d224d5a7a1a914cde0531f6',1,'test_training']]],
  ['test_5ftrain_5fseame_5fmodel_21',['test_train_seame_model',['../namespacetest__training.html#a3d252cac5ec117c6effda938ee25e6ca',1,'test_training']]],
  ['test_5ftraining_22',['test_training',['../namespacetest__training.html',1,'']]],
  ['test_5ftraining_2epy_23',['test_training.py',['../test__training_8py.html',1,'']]],
  ['testing_24',['testing',['../namespacetesting.html',1,'testing'],['../index.html#autotoc_md4',1,'Training and Testing'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2README.html#autotoc_md76',1,'Training and Testing']]],
  ['testing_2epy_25',['testing.py',['../testing_8py.html',1,'']]],
  ['the_20project_26',['Files in the Project',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md23',1,'']]],
  ['to_20tensorrt_27',['to tensorrt',['../index.html#autotoc_md11',1,'2. Converting YOLO to TensorRT'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2README.html#autotoc_md83',1,'2. Converting YOLO to TensorRT']]],
  ['to_20ubuntu_2020_2004_28',['to ubuntu 20 04',['../index.html#autotoc_md9',1,'1. Upgrading to Ubuntu 20.04'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2README.html#autotoc_md81',1,'1. Upgrading to Ubuntu 20.04']]],
  ['total_5fsize_29',['TOTAL_SIZE',['../namespacecamera__yolo__to__shm.html#a377ef03fa287c8ffe1010af4b91ebc22',1,'camera_yolo_to_shm']]],
  ['train_5fbatch0_2ejpg_30',['train_batch0.jpg',['../seame__n_2train__batch0_8jpg.html',1,'(Global Namespace)'],['../objects__training_2train__batch0_8jpg.html',1,'(Global Namespace)'],['../512_2train__batch0_8jpg.html',1,'(Global Namespace)'],['../new__dataset3_2train__batch0_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2train__batch0_8jpg.html',1,'(Global Namespace)'],['../seame__training_2train__batch0_8jpg.html',1,'(Global Namespace)'],['../objects_2train__batch0_8jpg.html',1,'(Global Namespace)']]],
  ['train_5fbatch1_2ejpg_31',['train_batch1.jpg',['../512_2train__batch1_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2train__batch1_8jpg.html',1,'(Global Namespace)'],['../seame__training_2train__batch1_8jpg.html',1,'(Global Namespace)'],['../seame__n_2train__batch1_8jpg.html',1,'(Global Namespace)'],['../objects__training_2train__batch1_8jpg.html',1,'(Global Namespace)'],['../objects_2train__batch1_8jpg.html',1,'(Global Namespace)'],['../new__dataset3_2train__batch1_8jpg.html',1,'(Global Namespace)']]],
  ['train_5fbatch2_2ejpg_32',['train_batch2.jpg',['../seame__training__512_2train__batch2_8jpg.html',1,'(Global Namespace)'],['../512_2train__batch2_8jpg.html',1,'(Global Namespace)'],['../seame__training_2train__batch2_8jpg.html',1,'(Global Namespace)'],['../seame__n_2train__batch2_8jpg.html',1,'(Global Namespace)'],['../objects__training_2train__batch2_8jpg.html',1,'(Global Namespace)'],['../objects_2train__batch2_8jpg.html',1,'(Global Namespace)'],['../new__dataset3_2train__batch2_8jpg.html',1,'(Global Namespace)']]],
  ['train_5fobjects_5fmodel_33',['train_objects_model',['../namespacetraining.html#a09e8ee81d2ef6dbf7e0da2f81373c86c',1,'training']]],
  ['train_5fseame_5fmodel_34',['train_seame_model',['../namespacetraining.html#ac89f59e609b31468b4bfc83ebc239835',1,'training']]],
  ['training_35',['training',['../namespacetraining.html',1,'']]],
  ['training_20and_20testing_36',['training and testing',['../index.html#autotoc_md4',1,'Training and Testing'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2README.html#autotoc_md76',1,'Training and Testing']]],
  ['training_2epy_37',['training.py',['../training_8py.html',1,'']]],
  ['true_38',['True',['../namespacetesting.html#a058614a5d36b5a9f7aaef7a7161d3f68',1,'testing']]],
  ['tt_20jetracer_20cpp_20tt_39',['tt jetracer cpp tt',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md51',1,'2. &lt;tt&gt;jetracer.cpp&lt;/tt&gt;'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md25',1,'2. &lt;tt&gt;jetracer.cpp&lt;/tt&gt;']]],
  ['tt_20jetracer_20hpp_20tt_40',['tt jetracer hpp tt',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md50',1,'1. &lt;tt&gt;jetracer.hpp&lt;/tt&gt;'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md24',1,'1. &lt;tt&gt;jetracer.hpp&lt;/tt&gt;']]],
  ['tt_20main_20cpp_20tt_41',['tt main cpp tt',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md52',1,'3. &lt;tt&gt;main.cpp&lt;/tt&gt;'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md26',1,'3. &lt;tt&gt;main.cpp&lt;/tt&gt;']]]
];
