var searchData=
[
  ['val_5fbatch0_5flabels_2ejpg_0',['val_batch0_labels.jpg',['../512_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../new__dataset3_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../objects_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../seame__n_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../seame__training_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2val__batch0__labels_8jpg.html',1,'(Global Namespace)']]],
  ['val_5fbatch0_5fpred_2ejpg_1',['val_batch0_pred.jpg',['../512_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../new__dataset3_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../objects_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../seame__n_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../seame__training_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2val__batch0__pred_8jpg.html',1,'(Global Namespace)']]],
  ['val_5fbatch1_5flabels_2ejpg_2',['val_batch1_labels.jpg',['../seame__training_2val__batch1__labels_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2val__batch1__labels_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch1__labels_8jpg.html',1,'(Global Namespace)'],['../objects_2val__batch1__labels_8jpg.html',1,'(Global Namespace)']]],
  ['val_5fbatch1_5fpred_2ejpg_3',['val_batch1_pred.jpg',['../objects_2val__batch1__pred_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch1__pred_8jpg.html',1,'(Global Namespace)'],['../seame__training_2val__batch1__pred_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2val__batch1__pred_8jpg.html',1,'(Global Namespace)']]],
  ['val_5fbatch2_5flabels_2ejpg_4',['val_batch2_labels.jpg',['../objects_2val__batch2__labels_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch2__labels_8jpg.html',1,'(Global Namespace)'],['../seame__training_2val__batch2__labels_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2val__batch2__labels_8jpg.html',1,'(Global Namespace)']]],
  ['val_5fbatch2_5fpred_2ejpg_5',['val_batch2_pred.jpg',['../objects_2val__batch2__pred_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch2__pred_8jpg.html',1,'(Global Namespace)'],['../seame__training_2val__batch2__pred_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2val__batch2__pred_8jpg.html',1,'(Global Namespace)']]],
  ['verify_5fdataset_6',['verify_dataset',['../namespacevisual__annotations.html#a56bbe44bd494e3c42ca0ac4fe991372a',1,'visual_annotations']]],
  ['visão_20geral_7',['Visão Geral',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md47',1,'']]],
  ['visual_5fannotations_8',['visual_annotations',['../namespacevisual__annotations.html',1,'']]],
  ['visual_5fannotations_2epy_9',['visual_annotations.py',['../visual__annotations_8py.html',1,'']]],
  ['visualize_5fannotations_10',['visualize_annotations',['../namespacevisual__annotations.html#a506bcb46caad07b808c9d106ab6460b4',1,'visual_annotations']]]
];
