var searchData=
[
  ['código_0',['Exemplo de Código',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md48',1,'']]],
  ['calculatetrackcenter_1',['calculateTrackCenter',['../namespacejetracer_1_1vision.html#a51e735807ed967fa0aa16ba980315f53',1,'jetracer::vision']]],
  ['camera_5fyolo_5fto_5fshm_2',['camera_yolo_to_shm',['../namespacecamera__yolo__to__shm.html',1,'']]],
  ['camera_5fyolo_5fto_5fshm_2epy_3',['camera_yolo_to_shm.py',['../camera__yolo__to__shm_8py.html',1,'']]],
  ['cap_4',['cap',['../namespacecamera__yolo__to__shm.html#a6efe3aa07ae44bd2c159202a442208ad',1,'camera_yolo_to_shm']]],
  ['change_5fannotation_5flabels_5',['change_annotation_labels',['../namespaceremap__classid.html#a923f6ddec09fc55e32e15b9919a68a73',1,'remap_classid']]],
  ['check_20status_6',['Check status',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2services__raspberryPi_2README.html#autotoc_md80',1,'']]],
  ['class_20details_7',['Class Details',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md16',1,'']]],
  ['class_5fcounts_8',['class_counts',['../namespacecount__labels.html#a835fcc63cb64ac6eb464e6ef1735ad62',1,'count_labels']]],
  ['classe_9',['Detalhes da Classe',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md42',1,'']]],
  ['classes_10',['classes',['../namespacecamera__yolo__to__shm.html#ae006807b8a140e534d9fc7b03f07db3e',1,'camera_yolo_to_shm']]],
  ['coco_5fto_5ftxt_11',['coco_to_txt',['../namespacecoco__txt.html#adf6a828f420294b46da800149bb8dabe',1,'coco_txt']]],
  ['coco_5ftxt_12',['coco_txt',['../namespacecoco__txt.html',1,'']]],
  ['coco_5ftxt_2epy_13',['coco_txt.py',['../coco__txt_8py.html',1,'']]],
  ['code_14',['Example Code',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md22',1,'']]],
  ['computer_5fvision_2ecpp_15',['computer_vision.cpp',['../computer__vision_8cpp.html',1,'']]],
  ['computer_5fvision_2ehpp_16',['computer_vision.hpp',['../computer__vision_8hpp.html',1,'']]],
  ['conf_17',['conf',['../namespacetesting.html#ab9941c8e55a286ff625d5794877a7d0b',1,'testing']]],
  ['conf_5fthreshold_18',['CONF_THRESHOLD',['../namespacecamera__yolo__to__shm.html#aa1e071d51a933617545cdfecfcdad9f2',1,'camera_yolo_to_shm']]],
  ['confusion_5fmatrix_2epng_19',['confusion_matrix.png',['../new__dataset3_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../objects_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../objects__training_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../seame__n_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../512_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../seame__training__512_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../seame__training_2confusion__matrix_8png.html',1,'(Global Namespace)']]],
  ['confusion_5fmatrix_5fnormalized_2epng_20',['confusion_matrix_normalized.png',['../new__dataset3_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../objects__training_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../512_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../objects_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../seame__n_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../seame__training_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../seame__training__512_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)']]],
  ['constructor_3a_21',['Constructor:',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md18',1,'']]],
  ['construtor_3a_22',['Construtor:',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md44',1,'']]],
  ['convert_5fbbox_5fto_5fsegmentation_23',['convert_bbox_to_segmentation',['../namespacebbox__seg.html#a96d0e5408dcf3702de543ddf98fc986c',1,'bbox_seg']]],
  ['converting_20yolo_20to_20tensorrt_24',['2. Converting YOLO to TensorRT',['../index.html#autotoc_md63',1,'']]],
  ['copy_5ffiles_25',['copy_files',['../namespacetraining.html#afec4c2a797c7e0adec7cade809245dea',1,'training']]],
  ['count_5fclass_5fids_26',['count_class_ids',['../namespacecount__labels.html#ac9bb963cf9677187850dc9d7c798906c',1,'count_labels']]],
  ['count_5flabels_27',['count_labels',['../namespacecount__labels.html',1,'']]],
  ['count_5flabels_2epy_28',['count_labels.py',['../count__labels_8py.html',1,'']]],
  ['coverage_20report_29',['Test Coverage Report',['../index.html#autotoc_md72',1,'']]],
  ['cpp_20tt_30',['cpp tt',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md5',1,'2. &lt;tt&gt;jetracer.cpp&lt;/tt&gt;'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md31',1,'2. &lt;tt&gt;jetracer.cpp&lt;/tt&gt;'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md6',1,'3. &lt;tt&gt;main.cpp&lt;/tt&gt;'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md32',1,'3. &lt;tt&gt;main.cpp&lt;/tt&gt;']]],
  ['created_20services_31',['🔧 Created Services',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2services__raspberryPi_2README.html#autotoc_md75',1,'']]]
];
