var searchData=
[
  ['backup_20strong_0',['&lt;strong&gt;1. Previous Model Backup&lt;/strong&gt;',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2do92b6b0ecbf00d55d82e017834694ab79.html#autotoc_md40',1,'']]],
  ['basic_20test_20strong_1',['&lt;strong&gt;1. Basic Test&lt;/strong&gt;',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2do92b6b0ecbf00d55d82e017834694ab79.html#autotoc_md44',1,'']]],
  ['bbox_5fseg_2',['bbox_seg',['../namespacebbox__seg.html',1,'']]],
  ['bbox_5fseg_2epy_3',['bbox_seg.py',['../bbox__seg_8py.html',1,'']]],
  ['benchmark_20results_4',['Benchmark Results',['../index.html#autotoc_md113',1,'']]],
  ['benchmarks_5',['YOLO Inference on Jetson Nano – Performance Improvements and Benchmarks',['../index.html#autotoc_md106',1,'']]],
  ['best_5f202507181755_20pt_6',['Migration to New YOLO Model - best_202507181755.pt',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2do92b6b0ecbf00d55d82e017834694ab79.html',1,'']]],
  ['blockquote_7',['blockquote',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2docs_2docs__main.html#autotoc_md50',1,'&lt;/blockquote&gt;'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2emergency__stop_2README.html#autotoc_md90',1,'&lt;/blockquote&gt;'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2README.html#autotoc_md63',1,'&lt;/blockquote&gt;']]],
  ['boxf1_5fcurve_2epng_8',['boxf1_curve.png',['../seame__training__512_2BoxF1__curve_8png.html',1,'(Global Namespace)'],['../512_2BoxF1__curve_8png.html',1,'(Global Namespace)'],['../new__dataset3_2BoxF1__curve_8png.html',1,'(Global Namespace)'],['../seame__n_2BoxF1__curve_8png.html',1,'(Global Namespace)'],['../objects_2BoxF1__curve_8png.html',1,'(Global Namespace)']]],
  ['boxp_5fcurve_2epng_9',['boxp_curve.png',['../512_2BoxP__curve_8png.html',1,'(Global Namespace)'],['../new__dataset3_2BoxP__curve_8png.html',1,'(Global Namespace)'],['../objects_2BoxP__curve_8png.html',1,'(Global Namespace)'],['../seame__n_2BoxP__curve_8png.html',1,'(Global Namespace)'],['../seame__training__512_2BoxP__curve_8png.html',1,'(Global Namespace)']]],
  ['boxpr_5fcurve_2epng_10',['boxpr_curve.png',['../seame__n_2BoxPR__curve_8png.html',1,'(Global Namespace)'],['../seame__training__512_2BoxPR__curve_8png.html',1,'(Global Namespace)'],['../objects_2BoxPR__curve_8png.html',1,'(Global Namespace)'],['../new__dataset3_2BoxPR__curve_8png.html',1,'(Global Namespace)'],['../512_2BoxPR__curve_8png.html',1,'(Global Namespace)']]],
  ['boxr_5fcurve_2epng_11',['boxr_curve.png',['../512_2BoxR__curve_8png.html',1,'(Global Namespace)'],['../seame__training__512_2BoxR__curve_8png.html',1,'(Global Namespace)'],['../seame__n_2BoxR__curve_8png.html',1,'(Global Namespace)'],['../objects_2BoxR__curve_8png.html',1,'(Global Namespace)'],['../new__dataset3_2BoxR__curve_8png.html',1,'(Global Namespace)']]],
  ['build_20run_12',['Build &amp; run',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2docs_2docs__main.html#autotoc_md59',1,'']]],
  ['button_20mapping_13',['Button Mapping',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2docs_2buttons__references.html#autotoc_md6',1,'']]],
  ['buttons_14',['buttons',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2docs_2buttons__references.html#autotoc_md8',1,'Action Buttons'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2docs_2buttons__references.html#autotoc_md7',1,'Shoulder Buttons']]],
  ['buttons_5freferences_2emd_15',['buttons_references.md',['../buttons__references_8md.html',1,'']]]
];
