var searchData=
[
  ['código_0',['Exemplo de Código',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md68',1,'']]],
  ['calculatetrackcenter_1',['calculateTrackCenter',['../namespacejetracer_1_1vision.html#a51e735807ed967fa0aa16ba980315f53',1,'jetracer::vision']]],
  ['camera_5fyolo_5fto_5fshm_2',['camera_yolo_to_shm',['../namespacecamera__yolo__to__shm.html',1,'']]],
  ['camera_5fyolo_5fto_5fshm_2epy_3',['camera_yolo_to_shm.py',['../camera__yolo__to__shm_8py.html',1,'']]],
  ['cap_4',['cap',['../namespacecamera__yolo__to__shm.html#a6efe3aa07ae44bd2c159202a442208ad',1,'camera_yolo_to_shm']]],
  ['change_5fannotation_5flabels_5',['change_annotation_labels',['../namespaceremap__classid.html#a923f6ddec09fc55e32e15b9919a68a73',1,'remap_classid']]],
  ['class_20details_6',['Class Details',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md36',1,'']]],
  ['class_5fcounts_7',['class_counts',['../namespacecount__labels.html#a835fcc63cb64ac6eb464e6ef1735ad62',1,'count_labels']]],
  ['classe_8',['Detalhes da Classe',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md62',1,'']]],
  ['classes_9',['classes',['../namespacecamera__yolo__to__shm.html#ae006807b8a140e534d9fc7b03f07db3e',1,'camera_yolo_to_shm']]],
  ['coco_5fto_5ftxt_10',['coco_to_txt',['../namespacecoco__txt.html#adf6a828f420294b46da800149bb8dabe',1,'coco_txt']]],
  ['coco_5ftxt_11',['coco_txt',['../namespacecoco__txt.html',1,'']]],
  ['coco_5ftxt_2epy_12',['coco_txt.py',['../coco__txt_8py.html',1,'']]],
  ['code_13',['Example Code',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md42',1,'']]],
  ['computer_5fvision_2ecpp_14',['computer_vision.cpp',['../computer__vision_8cpp.html',1,'']]],
  ['computer_5fvision_2ehpp_15',['computer_vision.hpp',['../computer__vision_8hpp.html',1,'']]],
  ['conf_16',['conf',['../namespacetesting.html#ab9941c8e55a286ff625d5794877a7d0b',1,'testing']]],
  ['conf_5fthreshold_17',['CONF_THRESHOLD',['../namespacecamera__yolo__to__shm.html#aa1e071d51a933617545cdfecfcdad9f2',1,'camera_yolo_to_shm']]],
  ['confusion_5fmatrix_2epng_18',['confusion_matrix.png',['../seame__training__512_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../512_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../new__dataset3_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../objects_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../objects__training_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../seame__n_2confusion__matrix_8png.html',1,'(Global Namespace)'],['../seame__training_2confusion__matrix_8png.html',1,'(Global Namespace)']]],
  ['confusion_5fmatrix_5fnormalized_2epng_19',['confusion_matrix_normalized.png',['../seame__training__512_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../seame__training_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../seame__n_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../objects__training_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../objects_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../new__dataset3_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)'],['../512_2confusion__matrix__normalized_8png.html',1,'(Global Namespace)']]],
  ['constructor_3a_20',['Constructor:',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md38',1,'']]],
  ['construtor_3a_21',['Construtor:',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md64',1,'']]],
  ['convert_5fbbox_5fto_5fsegmentation_22',['convert_bbox_to_segmentation',['../namespacebbox__seg.html#a96d0e5408dcf3702de543ddf98fc986c',1,'bbox_seg']]],
  ['converting_20yolo_20to_20tensorrt_23',['converting yolo to tensorrt',['../index.html#autotoc_md11',1,'2. Converting YOLO to TensorRT'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2README.html#autotoc_md83',1,'2. Converting YOLO to TensorRT']]],
  ['copy_5ffiles_24',['copy_files',['../namespacetraining.html#afec4c2a797c7e0adec7cade809245dea',1,'training']]],
  ['copy_5fmarkdown_5flines_25',['copy_markdown_lines',['../namespacecopy__readme.html#a3d6f8321debc586e21717894d010a982',1,'copy_readme']]],
  ['copy_5freadme_26',['copy_readme',['../namespacecopy__readme.html',1,'']]],
  ['copy_5freadme_2epy_27',['copy_readme.py',['../copy__readme_8py.html',1,'']]],
  ['count_5fclass_5fids_28',['count_class_ids',['../namespacecount__labels.html#ac9bb963cf9677187850dc9d7c798906c',1,'count_labels']]],
  ['count_5flabels_29',['count_labels',['../namespacecount__labels.html',1,'']]],
  ['count_5flabels_2epy_30',['count_labels.py',['../count__labels_8py.html',1,'']]],
  ['cpp_20tt_31',['cpp tt',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md25',1,'2. &lt;tt&gt;jetracer.cpp&lt;/tt&gt;'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md51',1,'2. &lt;tt&gt;jetracer.cpp&lt;/tt&gt;'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md26',1,'3. &lt;tt&gt;main.cpp&lt;/tt&gt;'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2pid__control_2README.html#autotoc_md52',1,'3. &lt;tt&gt;main.cpp&lt;/tt&gt;']]]
];
