var searchData=
[
  ['bbox_5fseg_0',['bbox_seg',['../namespacebbox__seg.html',1,'']]],
  ['bbox_5fseg_2epy_1',['bbox_seg.py',['../bbox__seg_8py.html',1,'']]],
  ['benchmark_20results_2',['benchmark results',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2README.html#autotoc_md85',1,'Benchmark Results'],['../index.html#autotoc_md13',1,'Benchmark Results']]],
  ['benchmarks_3',['benchmarks',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2README.html#autotoc_md78',1,'YOLO Inference on Jetson Nano – Performance Improvements and Benchmarks'],['../index.html#autotoc_md6',1,'YOLO Inference on Jetson Nano – Performance Improvements and Benchmarks']]],
  ['boxf1_5fcurve_2epng_4',['boxf1_curve.png',['../512_2BoxF1__curve_8png.html',1,'(Global Namespace)'],['../new__dataset3_2BoxF1__curve_8png.html',1,'(Global Namespace)'],['../objects_2BoxF1__curve_8png.html',1,'(Global Namespace)'],['../seame__n_2BoxF1__curve_8png.html',1,'(Global Namespace)'],['../seame__training__512_2BoxF1__curve_8png.html',1,'(Global Namespace)']]],
  ['boxp_5fcurve_2epng_5',['boxp_curve.png',['../objects_2BoxP__curve_8png.html',1,'(Global Namespace)'],['../512_2BoxP__curve_8png.html',1,'(Global Namespace)'],['../seame__training__512_2BoxP__curve_8png.html',1,'(Global Namespace)'],['../seame__n_2BoxP__curve_8png.html',1,'(Global Namespace)'],['../new__dataset3_2BoxP__curve_8png.html',1,'(Global Namespace)']]],
  ['boxpr_5fcurve_2epng_6',['boxpr_curve.png',['../objects_2BoxPR__curve_8png.html',1,'(Global Namespace)'],['../seame__n_2BoxPR__curve_8png.html',1,'(Global Namespace)'],['../seame__training__512_2BoxPR__curve_8png.html',1,'(Global Namespace)'],['../new__dataset3_2BoxPR__curve_8png.html',1,'(Global Namespace)'],['../512_2BoxPR__curve_8png.html',1,'(Global Namespace)']]],
  ['boxr_5fcurve_2epng_7',['boxr_curve.png',['../512_2BoxR__curve_8png.html',1,'(Global Namespace)'],['../new__dataset3_2BoxR__curve_8png.html',1,'(Global Namespace)'],['../objects_2BoxR__curve_8png.html',1,'(Global Namespace)'],['../seame__n_2BoxR__curve_8png.html',1,'(Global Namespace)'],['../seame__training__512_2BoxR__curve_8png.html',1,'(Global Namespace)']]]
];
