var searchData=
[
  ['val_5fbatch0_5flabels_2ejpg_0',['val_batch0_labels.jpg',['../512_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../new__dataset3_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../objects_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../seame__n_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../seame__training_2val__batch0__labels_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2val__batch0__labels_8jpg.html',1,'(Global Namespace)']]],
  ['val_5fbatch0_5fpred_2ejpg_1',['val_batch0_pred.jpg',['../objects_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../seame__training_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../seame__n_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../new__dataset3_2val__batch0__pred_8jpg.html',1,'(Global Namespace)'],['../512_2val__batch0__pred_8jpg.html',1,'(Global Namespace)']]],
  ['val_5fbatch1_5flabels_2ejpg_2',['val_batch1_labels.jpg',['../objects_2val__batch1__labels_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch1__labels_8jpg.html',1,'(Global Namespace)'],['../seame__training_2val__batch1__labels_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2val__batch1__labels_8jpg.html',1,'(Global Namespace)']]],
  ['val_5fbatch1_5fpred_2ejpg_3',['val_batch1_pred.jpg',['../seame__training_2val__batch1__pred_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2val__batch1__pred_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch1__pred_8jpg.html',1,'(Global Namespace)'],['../objects_2val__batch1__pred_8jpg.html',1,'(Global Namespace)']]],
  ['val_5fbatch2_5flabels_2ejpg_4',['val_batch2_labels.jpg',['../objects_2val__batch2__labels_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch2__labels_8jpg.html',1,'(Global Namespace)'],['../seame__training_2val__batch2__labels_8jpg.html',1,'(Global Namespace)'],['../seame__training__512_2val__batch2__labels_8jpg.html',1,'(Global Namespace)']]],
  ['val_5fbatch2_5fpred_2ejpg_5',['val_batch2_pred.jpg',['../seame__training__512_2val__batch2__pred_8jpg.html',1,'(Global Namespace)'],['../seame__training_2val__batch2__pred_8jpg.html',1,'(Global Namespace)'],['../objects__training_2val__batch2__pred_8jpg.html',1,'(Global Namespace)'],['../objects_2val__batch2__pred_8jpg.html',1,'(Global Namespace)']]],
  ['values_6',['Input Values',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2docs_2buttons__references.html#autotoc_md11',1,'']]],
  ['verbose_7',['verbose',['../namespaceextract__info__yolo__model.html#a55acb2b6e05b356774bf8ba13f01d829',1,'extract_info_yolo_model']]],
  ['verification_8',['Testing and Verification',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2docs_2buttons__references.html#autotoc_md12',1,'']]],
  ['verifications_20performed_20strong_9',['&lt;strong&gt;Verifications Performed&lt;/strong&gt;',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2do92b6b0ecbf00d55d82e017834694ab79.html#autotoc_md28',1,'']]],
  ['verify_5fdataset_10',['verify_dataset',['../namespacevisual__annotations.html#a56bbe44bd494e3c42ca0ac4fe991372a',1,'visual_annotations']]],
  ['vision_11',['vision',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2README.html',1,'PID Control + JetRacer Vision'],['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2emergency__stop_2README.html',1,'PID Control + JetRacer Vision']]],
  ['visual_20color_20thresholds_12',['Visual Color Thresholds',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2emergency__stop_2docs_2emergency__stop__system.html#autotoc_md85',1,'']]],
  ['visual_20indicators_20in_20stream_13',['4. Visual Indicators in Stream',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2emergency__stop_2docs_2emergency__stop__system.html#autotoc_md81',1,'']]],
  ['visual_5fannotations_14',['visual_annotations',['../namespacevisual__annotations.html',1,'']]],
  ['visual_5fannotations_2epy_15',['visual_annotations.py',['../visual__annotations_8py.html',1,'']]],
  ['visualize_5fannotations_16',['visualize_annotations',['../namespacevisual__annotations.html#a506bcb46caad07b808c9d106ab6460b4',1,'visual_annotations']]],
  ['vs_20new_20model_20strong_17',['&lt;strong&gt;Previous vs. New Model&lt;/strong&gt;',['../md__2home_2runner_2work_2ObjectDetectionAvoidance_2ObjectDetectionAvoidance_2complete__route_2do92b6b0ecbf00d55d82e017834694ab79.html#autotoc_md38',1,'']]]
];
